### ISSUE TITLE
Exact rules?

### ISSUE THREAD

**Issue by CodeBrauer** [codeinthedark/codeinthedark.github.io#2]
As already mentioned [here](https://www.reddit.com/r/web_design/comments/2jg0uc/code_in_the_dark_you_thought_you_knew_frontend/clbtkj5), there are no **exact** rules.

So what would be the answer to the question "DrDuPont" already mentioned?

**Comment by JoelBesada** [comment]
I've written a readme here in this repo now that should make it more clear. Please tell us if there's still something you'd like to know more about!

**Comment by CodeBrauer** [comment]
Thank you very much!
