### ISSUE TITLE
Ticket charge to cover event expenses

### ISSUE THREAD

**Issue by unmultimedio** [codeinthedark/codeinthedark.github.io#56]
Hi people!

I've got a simple question. How strict is this part of the `Readme` instructions?

```
Please read through and make sure you understand the license before using the Code in the Dark name or logo in your event. Community events may not be of commercial nature; you may not charge entrance or participation fees for Code in the Dark, neither a direct fee or indirect as part of another event.
```

I'm asking this because in the company I work for, we organized an event last October, it was great, but managing the costs and expenses of all of this was quite a struggle. We are thinking of organizing it again, but this time charging a basic entrance fee (no more than USD $15 to cover for the place rent, music, lights, food, and so on).

Would that be acceptable to do, using the original Code In The Dark logo, rules, editor, and all of this?

**Comment by unmultimedio** [comment]
Hello @JoelBesada @siavashg @grant Any news here? Thank you!!!

**Comment by grant** [comment]
I’m not an owner of this project.

**Comment by JoelBesada** [comment]
Hey @unmultimedio. Our core belief is that Code in the Dark should be an event open to everyone and free to both attend and participate in, so the rule stands as it is now. We would like to encourage you however to consider alternative ways to cover the event costs, such as charging for food and drinks for example. 

I hope you understand where we are coming from with this.

**Comment by unmultimedio** [comment]
Understood @JoelBesada, thanks for your response!
