### ISSUE TITLE
Is this project still maintained? 

### ISSUE THREAD

**Issue by omonk** [codeinthedark/codeinthedark.github.io#78]
I'd like to organise an event but I can see several PRs from many months ago that haven't been merged?

**Comment by sickDevelopers** [comment]
Same issue here, is there anybody alive @ tictail? :smile: I mean, I know you merged with Shopify, but since this has become a global event, colud anybody keep this repo alive?
Or just switch ownership to someone who will

**Comment by omonk** [comment]
Seems a shame doesn't it! A lot of people loved this concept... :(

**Comment by JoelBesada** [comment]
Hi, we're sorry for leaving this repo unattended for a while. As @sickDevelopers mentioned, we've merged with Shopify so we have had our focus occupied by other things for a while. I'm happy however to say that we do plan to keep this project alive again now! 

If you have any upcoming events, please submit a PR and we'll happily have them merged into the website.
